### ISSUE TITLE
Pagination Issues

### ISSUE THREAD

**Issue by seanogdev** [mdcpepper/fetch#1]
Hi,

I'm not sure how actively this is being developed but I'm running into issues with paginating the query, adding filtering to the query and the fetch plugin.

My current setup is as follows

```
{% set params = {
    section : 'restaurants',
    limit: 18,
    search : (searchQuery is defined) ? searchQuery
    }
%}

{% set query = craft.entries(params) %}

{% if relatedTo | length > 1 %}
    {% set query = query.relatedTo(relatedTo) %}
{% endif %}

{% if searchQuery | length %}
    {% set query = query.search(searchQuery) %}
{% endif %}

{% do craft.fetch.assets(query.find(), 'images') %}
```

and my template code

```
    {% paginate query as restaurantList %}

    {% for entry in restaurantList %}

    {% set image = entry.fetched('images')[0] %}
    {{image code }}
    {% endfor %}

    {{ pagination nav code }}

    {% endpaginate %}
```

Main issue I'm getting is 

`Craft\EntryModel and its behaviors do not have a method or closure named "fetched".`

But only on the `/page/n` pages

**Comment by mdcpepper** [comment]
I think you'll want to fetch the assets from inside the `{% paginate %}` tag so you're getting each page's worth, not the images for the whole query. Try this:

```
{% set params = {
    section : 'restaurants',
    limit: 18,
    search : (searchQuery is defined) ? searchQuery
    }
%}

{% set query = craft.entries(params) %}

{% if relatedTo | length > 1 %}
    {% set query = query.relatedTo(relatedTo) %}
{% endif %}

{% if searchQuery | length %}
    {% set query = query.search(searchQuery) %}
{% endif %}

 {% paginate query as restaurantList %}

    {% for entry in craft.fetch.assets(restaurantList.find(), 'images') %}
        {% set image = entry.fetched('images')[0] %}
        {{image code }}
    {% endfor %}

    {{ pagination nav code }}

{% endpaginate %}
```

**Comment by seanogdev** [comment]
Ah yep, that would make sense... Thanks!

**Comment by mdcpepper** [comment]
No problem! Let me know if it works or you hit any other issues. This plugin isn't really under proper development as I'm pretty sure the N+1 issue will be solvable with Craft 3, but I'd like to keep it at least basically working for 2.x.

**Comment by seanogdev** [comment]
Yeah I'm just running into serious performance issues with my current setup & high traffic, trying all while still in Craft 2. Need to try anything I can to mitigate :)
