### ISSUE TITLE
Related elements limit is set to 100

### ISSUE THREAD

**Issue by wesrice** [mdcpepper/fetch#6]
I have an interesting issue.

I have a set of about thirty elements and I want to get all of their assets. Each element has 3-5 assets.
This means that over 100 assets will need to be retrieved for my source elements.

However, I'm running into an issue with this code.

```
$elements = craft()->elements->getCriteria($elementType)
                ->id($targetIds)
                ->indexBy('id')
                ->locale($sourceLocale)
                ->find();
```

The limit is not set the criteria model, so it inherits Craft's default limit of 100, which is less than the amount needed in my use case.

The simple thing is to add `->limit(null)`, but I'm not sure what negative effects this could have on usage. I'm thinking that it won't have any effect, since there is no sort of pagination on the related elements. If the performance is slow, then it can be up to the developer to limit the number of source elements.

I don't really think it will be a bad thing to add the null limit, so I'm going to make a pull request to change this. I just wanted to explain it a bit.

**Comment by wesrice** [comment]
#7

**Comment by mdcpepper** [comment]
Hi Wes, 

Thanks for this, I agree there shouldn't be any issues with the `null` limit, unless I'm missing some use-cases for this plugin... If necessary perhaps there's a way to allow for proper criteria to be passed through to that.

Thanks for the pull request, I've merged it in and I'll cut a proper release soon, few more bits I'd like to add for 2.5!
